### ISSUE TITLE
Revision 23 de Marzo

### ISSUE THREAD

**Issue by gera-gpz** [JoseVarela321/P2_16100286#1]
Presentó el mismo formulario que su compañero de proyecto,  
me hubiera hecho otro formulario del mismo proyecto !!! pero se lo tomaré en cuenta

Al igual que su companero (Guardado) no entrego la T4
Mentengase al pendiente hay que entregar lo trabajos
Los tomaré en cuenta para evaluación

**Comment by JoseVarela321** [comment]
Buenas noches inge, una disculpa pensamos que era en equipo por qué como
dijo que lo hiciéramos respecto a nuestro proyecto pensamos que era en
equipo:( una disculpa!

**Comment by gera-gpz** [comment]
No se procupe joven
Confirmen por favor el mensaje que publiqué en Classroom 
Y entreguen el modelo relacional de su base de datos de proyecto.
